// This file is generated by Slice Machine. Update with care!

import Card from './Card';
import Carousel from './Carousel';
import Hero from './Hero';
import Image from './Image';
import ImageCards from './ImageCards';
import Producer from './Producer';
import Quote from './Quote';
import Region from './Region';
import Text from './Text';
import TextWithImage from './TextWithImage';

export {
	Card,
	Carousel,
	Hero,
	Image,
	ImageCards,
	Producer,
	Quote,
	Region,
	Text,
	TextWithImage,
};

export const components = {
	card: Card,
	producer: Carousel,
	hero: Hero,
	image: Image,
	image_cards: ImageCards,
	producer: Producer,
	quote: Quote,
	region: Region,
	text: Text,
	text_with_image: TextWithImage,
};
